# Generated by Django 2.2.16 on 2022-03-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220314_1722'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartrecipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_cart'),
        ),
    ]
